# Pemerolehan Informasi 
# Modul 2

### 205314159
### Paulus Caesario Dito Putra Hartono

## Nomor 2

### a. Impor pandas

In [ ]:
import pandas as pd

### b. Membuka file

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/perolehan-informasi/files/praktikum-2/video-store.csv")

### c. Melihat header

In [ ]:
for col in df.columns:
  print(col)

Cust ID
Gender
Income
Age
Rentals
Avg Per Visit
Incidentals
Genre

### d. Melihat data tertentu

In [ ]:
print(df['Genre'])

0     Action
1      Drama
2     Comedy
3      Drama
4     Action
5     Action
6      Drama
7     Action
8     Comedy
9     Comedy
10     Drama
11    Action
12    Comedy
13     Drama
14    Comedy
15    Action
16     Drama
17    Action
18    Comedy
19    Comedy
20     Drama
21     Drama
22    Comedy
23     Drama
24    Comedy
25    Action
26     Drama
27    Comedy
28    Action
29    Action
30    Comedy
31     Drama
32    Action
33    Action
34    Action
35    Comedy
36    Comedy
37     Drama
38    Comedy
39    Action
40     Drama
41    Action
42     Drama
43     Drama
44     Drama
45     Drama
46     Drama
47     Drama
48    Action
49    Action
Name: Genre, dtype: object

### e. Fungsi matematika

In [ ]:
df['Age'].mean()
df['Age'].quantile()
df['Age'].sum()

1610

### f. Menambahkan kolom pada data frame

In [ ]:
data=[]
min=df['Age'].min()
max=df['Age'].max()
for x in df['Age']:
  data.append((x-min)/(max-min))
df['Age_minmax']=data
print(df)

    Cust ID Gender    Income  Age  Rentals  Avg Per Visit Incidentals   Genre  \
0         1      M  $45,000    25       27            2.5         Yes  Action
1         2      F  $54,000    33       12            3.4          No   Drama
2         3      F  $32,000    20       42            1.6          No  Comedy
3         4      F  $59,000    70       16            4.2         Yes   Drama
4         5      M  $37,000    35       25            3.2         Yes  Action
5         6      M  $18,000    20       33            1.7          No  Action
6         7      F  $29,000    45       19            3.8          No   Drama
7         8      M  $74,000    25       31            2.4         Yes  Action
8         9      M  $69,500    21       18            2.1          No  Comedy
9        10      F  $65,000    40       21            3.3          No  Comedy
10       11      F  $41,000    22       48            2.3         Yes   Drama
11       12      F  $26,000    22       29            2.9         Yes  Action
12       13      M  $83,000    46       14            3.6          No  Comedy
13       14      M  $45,000    36       24            2.7          No   Drama
14       15      M  $68,000    50       36            2.7         Yes  Comedy
15       16      M  $17,000    19       26            2.2         Yes  Action
16       17      M  $36,000    35       28            3.5         Yes   Drama
17       18      F   $2,000    16       39            1.8         Yes  Action
18       19      F  $24,000    25       41            3.1          No  Comedy
19       20      M  $12,000    16       23            2.2         Yes  Comedy
20       21      F  $47,000    52       11            3.1          No   Drama
21       22      M  $25,000    33       16            2.9         Yes   Drama
22       23      F   $2,000    15       30            2.5          No  Comedy
23       24      F  $79,000    35       22            3.8         Yes   Drama
24       25      M   $1,000    16       25            1.4         Yes  Comedy
25       26      F  $56,000    35       40            2.6         Yes  Action
26       27      F  $62,000    47       32            3.6          No   Drama
27       28      M  $57,000    52       22            4.1          No  Comedy
28       29      F  $15,000    18       37            2.1         Yes  Action
29       30      M  $41,000    25       17            1.4         Yes  Action
30       31      F  $49,000    56       15            3.2          No  Comedy
31       32      M  $47,000    30       21            3.1         Yes   Drama
32       33      M  $23,000    25       28            2.7          No  Action
33       34      F  $29,000    32       19            2.9         Yes  Action
34       35      M  $74,000    29       43            4.6         Yes  Action
35       36      F  $29,000    21       34            2.3          No  Comedy
36       37      M  $89,000    46       12            1.2          No  Comedy
37       38      M  $41,000    38       20            3.3         Yes   Drama
38       39      F  $68,000    35       19            3.9          No  Comedy
39       40      M  $17,000    19       32            1.8          No  Action
40       41      F  $50,000    33       17            1.4          No   Drama
41       42      M  $32,000    25       26            2.2         Yes  Action
42       43      F  $49,000    28       48            3.3         Yes   Drama
43       44      M  $35,000    24       24            1.7          No   Drama
44       45      M  $56,000    45       30            3.5         Yes   Drama
45       46      F  $57,000    43        9            1.1          No   Drama
46       47      F  $69,000    35       22            2.8         Yes   Drama
47       48      F  $52,000    47       14            1.6          No   Drama
48       49      M  $31,000    30       42            3.4         Yes  Action
49       50      M  $24,000    20       33            4.7          No  Action

    Age_minmax
0     0.181818
1     0.327273
2     0.090909
3     1.000000
4     0.363636
5     0.090909
6     0.545455
7     0.181818
8     0.109091
9     0.454545
10    0.127273
11    0.127273
12    0.563636
13    0.381818
14    0.636364
15    0.072727
16    0.363636
17    0.018182
18    0.181818
19    0.018182
20    0.672727
21    0.327273
22    0.000000
23    0.363636
24    0.018182
25    0.363636
26    0.581818
27    0.672727
28    0.054545
29    0.181818
30    0.745455
31    0.272727
32    0.181818
33    0.309091
34    0.254545
35    0.109091
36    0.563636
37    0.418182
38    0.363636
39    0.072727
40    0.327273
41    0.181818
42    0.236364
43    0.163636
44    0.545455
45    0.509091
46    0.363636
47    0.581818
48    0.272727
49    0.090909

## Nomor 3

### a. Impor request, BeautifulSoup, dan Pandas

In [ ]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

### b. Mengakses website

In [ ]:
page=requests.get("https://forecast.weather.gov/MapClick.php?lat=37.7772&lon=-122.4168#.YyFMmdJByV4")
soup = bs(page.content, 'html.parser')
seven_day = soup.find(id="seven-day-forecast")
forecast_items = seven_day.find_all(class_="tombstone-container")
tonight = forecast_items[0]
print(tonight.prettify())

<div class="tombstone-container">
 <p class="period-name">
  Tonight
  <br/>
  <br/>
 </p>
 <p>
  <img alt="Tonight: Mostly cloudy, with a low around 59. West wind 11 to 14 mph, with gusts as high as 18 mph. " class="forecast-icon" src="newimages/medium/nbkn.png" title="Tonight: Mostly cloudy, with a low around 59. West wind 11 to 14 mph, with gusts as high as 18 mph. "/>
 </p>
 <p class="short-desc">
  Mostly Cloudy
 </p>
 <p class="temp temp-low">
  Low: 59 °F
 </p>
</div>

### c. Mengambil data hari dari website

In [ ]:
period_tags=seven_day.select(".tombstone-container .period-name")
periods = [pt.get_text() for pt in period_tags]
periods

['Tonight',
 'Thursday',
 'ThursdayNight',
 'Friday',
 'FridayNight',
 'Saturday',
 'SaturdayNight',
 'Sunday',
 'SundayNight']

### d. Menampilkan data tujuh hari dari website

In [ ]:
short_descs = [sd.get_text() for sd in seven_day.select(".tombstone-container .short-desc")]

temps = [t.get_text() for t in
seven_day.select(".tombstone-container .temp")]

descs = [d['title'] for d in seven_day.select('.tombstone-container img')]

print(short_descs)
print(temps)
print(descs)

['Mostly Cloudy', 'Mostly Sunnythen Sunnyand Breezy', 'Partly Cloudy', 'BecomingSunny', 'Mostly Clear', 'Mostly Sunny', 'Slight ChanceShowers', 'ChanceShowers', 'ChanceShowers']
['Low: 59 °F', 'High: 69 °F', 'Low: 57 °F', 'High: 70 °F', 'Low: 57 °F', 'High: 69 °F', 'Low: 58 °F', 'High: 69 °F', 'Low: 58 °F']
['Tonight: Mostly cloudy, with a low around 59. West wind 11 to 14 mph, with gusts as high as 18 mph. ', 'Thursday: Mostly sunny, with a high near 69. Breezy, with a west wind 10 to 15 mph increasing to 17 to 22 mph in the afternoon. Winds could gust as high as 28 mph. ', 'Thursday Night: Partly cloudy, with a low around 57. West wind 10 to 20 mph, with gusts as high as 25 mph. ', 'Friday: Partly sunny, then gradually becoming sunny, with a high near 70. West wind 13 to 18 mph, with gusts as high as 23 mph. ', 'Friday Night: Mostly clear, with a low around 57. West wind 11 to 21 mph, with gusts as high as 25 mph. ', 'Saturday: Mostly sunny, with a high near 69.', 'Saturday Night: A 20 percent chance of showers after 11pm.  Mostly cloudy, with a low around 58.', 'Sunday: A chance of showers.  Partly sunny, with a high near 69.', 'Sunday Night: A chance of showers.  Mostly cloudy, with a low around 58.']

### e. Menampilkan tabel data tujuh hari

In [ ]:
# weather = pd.DataFrame.from_dict({
#     "period": periods,
#     "short_desc": short_descs,
#     "temp": temps,
#     "desc": descs,
# }, orient='index')
# weather = weather.transpose()
# weather


## Code diatas digunakan jika nilai dari tabel ada yang kosong

weather = pd.DataFrame({
  "period": periods,
  "short_desc": short_descs,
  "temp": temps,
  "desc": descs
})
weather

,period,short_desc,temp,desc
0,Tonight,Mostly Cloudy,Low: 59 °F,"Tonight: Mostly cloudy, with a low around 59. ..."
1,Thursday,Mostly Sunnythen Sunnyand Breezy,High: 69 °F,"Thursday: Mostly sunny, with a high near 69. B..."
2,ThursdayNight,Partly Cloudy,Low: 57 °F,"Thursday Night: Partly cloudy, with a low arou..."
3,Friday,BecomingSunny,High: 70 °F,"Friday: Partly sunny, then gradually becoming ..."
4,FridayNight,Mostly Clear,Low: 57 °F,"Friday Night: Mostly clear, with a low around ..."
5,Saturday,Mostly Sunny,High: 69 °F,"Saturday: Mostly sunny, with a high near 69."
6,SaturdayNight,Slight ChanceShowers,Low: 58 °F,Saturday Night: A 20 percent chance of showers...
7,Sunday,ChanceShowers,High: 69 °F,"Sunday: A chance of showers. Partly sunny, wi..."
8,SundayNight,ChanceShowers,Low: 58 °F,Sunday Night: A chance of showers. Mostly clo...

### f. Mengambil data temperatur dan diubah menjadi tipe int

In [ ]:
temp_nums = weather["temp"].str.extract("(?P<temp_num>\d+)", expand=False)
weather["temp_num"] = temp_nums.astype('int')
temp_nums

0    59
1    69
2    57
3    70
4    57
5    69
6    58
7    69
8    58
Name: temp_num, dtype: object

### g. Tampilkan rata-rata suhu cuaca

In [ ]:
total = 0
for x in temp_nums:
  total = total + int(x)

avg = total/temp_nums.size
avg

62.888888888888886

### h. Meilhat cuaca pada malam hari mengandung temperatur rendah

In [ ]:
is_night = weather['temp'].str.contains('Low')
weather['is_night'] = is_night
is_night

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8     True
Name: temp, dtype: bool

### i. Tampilkan seluruh cuaca pada malam hari!

In [ ]:
# weather.get(['period', 'is_night'])[weather['is_night']]

# a = weather[is_night & (weather['temp_num'] > 58)]
# a

weather.get(weather['is_night'])

,period,short_desc,temp,desc,temp_num,is_night
0,Tonight,Mostly Cloudy,Low: 59 °F,"Tonight: Mostly cloudy, with a low around 59. ...",59,True
2,ThursdayNight,Partly Cloudy,Low: 57 °F,"Thursday Night: Partly cloudy, with a low arou...",57,True
4,FridayNight,Mostly Clear,Low: 57 °F,"Friday Night: Mostly clear, with a low around ...",57,True
6,SaturdayNight,Slight ChanceShowers,Low: 58 °F,Saturday Night: A 20 percent chance of showers...,58,True
8,SundayNight,ChanceShowers,Low: 58 °F,Sunday Night: A chance of showers. Mostly clo...,58,True

### j. Menyimpan data

In [ ]:
weather.to_csv('weather.csv')

## Nomor 4

In [1]:
# https://jogja.tribunnews.com/2022/09/14/4-rekomendasi-kuliner-bubur-ayam-di-jogja-cocok-buat-menu-sarapan

import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

url = "https://jogja.tribunnews.com/2022/09/14/4-rekomendasi-kuliner-bubur-ayam-di-jogja-cocok-buat-menu-sarapan?page=2"

page=requests.get(url)
soup = bs(page.content, 'html.parser')

head_tag = soup.head

body_tag = soup.body

judul = head_tag.contents[1].contents[0]

# print('Judul: ', judul)

tanggal = body_tag.time.contents[0]

# print('Tgl Penulisan: ', tanggal)

img_thumb = body_tag.find_all('img', class_='imgfull')[0]['src']

# print('Url Thumbnail: ', img_thumb)

strong_str = body_tag.find_all('strong')

bolded_text = []
for x in strong_str:
  bolded_text.append(x.text)

# print('Teks ter-bold: ', bolded_text)

paging = body_tag.find_all('div', {'class':'paging'})

pages = []
if(url[-3:]!='all'):
  pages = paging[0].find_all('a')

# print(pages)

pagination_link = []

for x in pages:
  pagination_link.append(x['href'])

# print(len(pagination_link))
# print(pagination_link)

num_of_pages = len(pagination_link)

embedded_links = body_tag.find_all('iframe')

list_of_links = []
for x in embedded_links:
  list_of_links.append(x['src'])

table = pd.DataFrame.from_dict({
  "Judul": judul,
  "Tanggal": tanggal,
  "Thumbnail": img_thumb,
  "Bolded-Tags": bolded_text,
  "Num-of-Pages": num_of_pages,
  "Embedded-links": list_of_links
}, orient='index')

# table = table.transpose() 

table.to_csv('tribunjogja-onepage.csv')

table

                                                                0
Judul           4 Rekomendasi Kuliner Jogja Menyantap Bubur Ay...
Tanggal                         Rabu, 14 September 2022 11:16 WIB
Thumbnail       https://t-2.tstatic.net/jogja/foto/bank/images...
Bolded-Tags     [3. Bubur Ayamnya Opa,  Baca juga: 10 Rekomend...
Num-of-Pages                                                    3
Embedded-links  [https://www.googletagmanager.com/ns.html?id=G...

In [ ]:
img_thumb = body_tag.find_all('img', class_='imgfull')[0]['height']

img_thumb

'393'

In [ ]:
## Scraping specific page (per-pagination)

def scrap_boldText(webpage, page):
  url = webpage + '?page=' + str(page)
  r = requests.get(url)

  soup = bs(r.content, 'html.parser')

  body_tag = soup.body

  strong_str = body_tag.find_all('strong')

  bolded_text = []
  for x in strong_str:
    bolded_text.append(x.text)

  return bolded_text

scrap_boldText("https://jogja.tribunnews.com/2022/09/14/4-rekomendasi-kuliner-bubur-ayam-di-jogja-cocok-buat-menu-sarapan", 'all')

['TRIBUNJOGJA.COM -',
 '1. Bubur Rempah DMR',
 '2. Burnesia',
 '3. Bubur Ayamnya Opa',
 ' Baca juga: 10 Rekomendasi Kuliner Malam Jogja Selalu Ramai Pengunjung',
 '4. Bubur Hayam Kotabaru',
 '(MG/Halimatus Sakdiah)']